name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Lightsail
      env:
        HOST: ${{ secrets.LIGHTSAIL_HOST }}
        USER: ${{ secrets.LIGHTSAIL_USER }}
        KEY: ${{ secrets.LIGHTSAIL_KEY }}
      run: |
        echo "$KEY" > ~/key.pem
        chmod 600 ~/key.pem
        ssh -o StrictHostKeyChecking=no -i ~/key.pem $USER@$HOST 'cd ~/myapp && git pull && source venv/bin/activate && pkill streamlit && pip install -r requirements.txt && nohup streamlit run app.py &'