[connections.mysql]
dialect = "mysql"
host = "ls-0d272b6d055951932dd7f1404e6322222517d8bd.caoof4uxeqnq.us-east-1.rds.amazonaws.com"
port = 8501
database = "dbmaster_deb"
username = "subaward_user"
password = "ict_use_webapp"